### ISSUE TITLE
Add a date and location field for sys_file_collection

### ISSUE THREAD

**Issue by liayn** [freshworkx/typo3-image-gallery#16]
**Is your feature request related to a problem? Please describe.**
It would make the extension perfect for showing event images, if each gallery would also have a date(time) and location field.
It would make the galleries sortable by these fields.

**Describe the solution you'd like**
Add the fields to the file collection

**Describe alternatives you've considered**
Putting stuff into the description field causes data to be less structured, allowing less flexible output rendering in Fluid.

**Comment by flossels** [comment]
Hi Markus,

thanks for this feature request and, of course, for using our extension. Yore feature is implemented in the current master and I will schedule a release for the next days. 
Currently there is only the possibility to sort galleries manually (in the plugin configuration). Only the files contained by a file collection can be sorted according to some criteria. Is this fine for you?

Cheers
Flo

**Comment by liayn** [comment]
Hi!

Thanks a lot. Let me see if I can provide a PR to have the galleries sortable by date.
Basic usage: Put a plugin on a page to "list all galleries sorted by eventdate desc"

**Comment by freshworkx** [comment]
Closed as date and location field have been included for a long time. If you have any further requests, please create a new issue.
