### ISSUE TITLE
TYPO3 11.5

### ISSUE THREAD

**Issue by Hobokens** [freshworkx/typo3-image-gallery#26]
Hi,
Thanks for the nice extension. Do you plan an upgrade to the latest version?

Regards
Hobokens

**Comment by Esders** [comment]
Hi! We are at the moment quite busy with project-related tasks so I am not sure about the realistic timeline for this - sorry!

**Comment by freshworkx** [comment]
Closed, as TYPO3 11.5 compatibility with version 5.2 is already given.
