### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Hobokens** [freshworkx/typo3-image-gallery#27]
**Is your feature request related to a problem? Please describe.**
If you have a lot of images, it would be nice to have a pagination,

**Describe the solution you'd like**
Add the new pagination to the extension.

**Comment by Esders** [comment]
Hi! Thanks for the suggestion - we will check on that!

**Comment by freshworkx** [comment]
@Hobokens Is the need for pagination still relevant for you?

**Comment by Hobokens** [comment]
I don't use the extension anymore but pagination might be useful for others.
