### ISSUE TITLE
The cropVariant do not work in the Detailview

### ISSUE THREAD

**Issue by florianstieglbauer** [freshworkx/typo3-image-gallery#59]
When I try to use the CropVariant to achieve a better image crop for certain pictures, unfortunately, it doesn't work.
_bm_image_gallery/Resources/Private/Partials/Image.html_
```
<f:image image="{item}" class="c-gallery__image figure-img img-fluid" width="{settings.images.width}"
         height="{settings.images.height}" maxWidth="{settings.images.maxWidth}" maxHeight="{settings.images.maxHeight}"
         alt="{item.description}" cropVariant="mycustomcrop"/>
```
I believe the issue lies in outputting the original image UID. Instead, the image ID from sys_file_reference is needed for the cropping to function properly.

Example:
![screenshot](https://github.com/user-attachments/assets/3fe8ec80-dd48-4904-9603-499dd9631ed4)

The UID of {item} is 308, which is the original UID from the file list of the image. In the file collection, the ID is 251. When I manually enter this ID in my f:image ViewHelper, the cropped image is displayed correctly.

Florian

**Comment by freshworkx** [comment]
Back from vacation, will check issue soon, thanks for reporting

**Comment by freshworkx** [comment]
@florianstieglbauer can you provide some more information about your configuration? What does your crop variant look like? And which plugin configuration are you using at this point?

**Comment by freshworkx** [comment]
@florianstieglbauer  unfortunately it is not easy to implement for all use cases, this does not work without major changes. Therefore, I refer at this point to new issue #60.

The file reference / crop variants feature is coming in the next major version.

**Comment by florianstieglbauer** [comment]
@freshworkx Thank you! I wanted to give it a try myself, but I quickly realized that this feature requires extensive changes, or that I simply lack the necessary knowledge.

I had to make some modifications to your extension because I implemented the output of individual galleries through categories. In the plugin, you can select a category, and then all galleries with that category will be displayed.

Regarding your question:
In my site package, I override the `sys_file_reference.php` with the following value. The image cropping function should have worked on my detail page.

TCA/Overrides/sys_file_reference.php
`<?php
$GLOBALS['TCA']['sys_file_reference']['columns']['crop']['config'] = [
    'type' => 'imageManipulation',
    'cropVariants' => [
        'default' => [
            'title' => 'Default',
            'allowedAspectRatios' => [
                'NaN' => [
                    'title' => 'Frei',
                    'value' => 0.0
                ],
                '1:1' => [
                    'title' => 'Quadrat 1:1',
                    'value' => 1 / 1
                ],
                '3:2' => [
                    'title' => 'Querformat 3:2',
                    'value' => 3 / 2
                ],

                '2:3' => [
                    'title' => 'Hochformat 2:3',
                    'value' => 2 / 3
                ],
            ],
            'selectedRatio' => '3:2',
        ],
    ],
];
?>
`

**Comment by freshworkx** [comment]
close this issue in favor of #60
